#!/usr/bin/env bash
# vim: set ts=4 sw=4 sts=4 et:
# bootstrap installs things.
set -u

cd "$(dirname "$0")/.." || exit 1
DOTFILES_ROOT=$(pwd)

echo "DOTFILES_ROOT ${DOTFILES_ROOT}"

# Source reusable bash functions
source "${DOTFILES_ROOT}"/bash/functions.bash

echo ''

function link_file() {
    local src="${1}" dst="${2}"

    local overwrite='' backup='' skip=''
    local action=''

    if [ -f "${dst}" ] || [ -d "${dst}" ] || [ -L "${dst}" ]; then
        if [ "$overwrite_all" == "false" ] && [ "$backup_all" == "false" ] && [ "$skip_all" == "false" ]; then
            local currentSrc="$(readlink ${dst})"

            if [ "$currentSrc" == "$src" ]; then
                skip=true;
            else
                user "File already exists: $dst ($(basename "$src")), what do you want to do?\n\
                    [s]kip, [S]kip all, [o]verwrite, [O]verwrite all, [b]ackup, [B]ackup all?"
                read -n 1 action
                case "${action}" in
                    o )
                        overwrite=true
                        ;;
                    O )
                        overwrite_all=true
                        ;;
                    b )
                        backup=true
                        ;;
                    B )
                        backup_all=true
                        ;;
                    s )
                        skip=true
                        ;;
                    S )
                        skip_all=true
                        ;;
                    * )
                        ;;
                esac

            fi
        fi

        overwrite=${overwrite:-$overwrite_all}
        backup=${backup:-$backup_all}
        skip=${skip:-$skip_all}

        if [ "$overwrite" == "true" ]; then
            rm -rf "$dst"
            success "removed $dst"
        fi

        if [ "$backup" == "true" ]; then
            mv "$dst" "${dst}.backup"
            success "moved $dst to ${dst}.backup"
        fi

        if [ "$skip" == "true" ]; then
            success "skipped $src"
        fi
    fi

    if [ "$skip" != "true" ]; then  # "false" or empty
        ln -s "$1" "$2"
        success "linked $1 to $2"
    fi

    # Indicate the the boostrap script has been run
    touch "${DOTFILES_ROOT}/.initialized"
}

function install_dotfiles() {
    info 'installing dotfiles'

    local overwrite_all=false skip_all=false

    if [ -f "${DOTFILES_ROOT}/.initialized" ]
    then
        local backup_all=false
    else
        # Backup all on the first run.
        local backup_all=true
    fi

    for src in $(find -H "$DOTFILES_ROOT" -maxdepth 2 -name '*.symlink')
    do
        dst="$HOME/.$(basename "${src%.*}")"
        link_file "$src" "$dst"
    done
}

create_my_dirs() {
    for tmpdir in ~/bitbucket ~/github ~/tmp ~/tmpvim
    do
        if [ ! -d ${tmpdir} ]; then
            info "Creating ${tmpdir}"
            mkdir ${tmpdir}
            success "Created ${tmpdir}"
        fi
    done
}

function mac_install_homebrew {
    if type brew > /dev/null; then
        echo "Homebrew already installed"
    else
        /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    fi
}

function mac_brew_install_stuff {
    brew update

    brew install ack awscli bash-completion findutils fzf neovim p7zip the_silver_searcher tree wget zsh zsh-completions
}

function mac_brew_cask_install_stuff {
    brew update
    brew tap homebrew/cask-fonts

    brew cask install font-hack font-source-code-pro keepassxc vimr
}

###############################################################################

create_my_dirs

install_dotfiles

if [ "$(uname)" == "Darwin" ]; then
    info "Mac detected"
    mac_install_homebrew
    mac_brew_install_stuff
    mac_brew_cask_install_stuff
    osx/grml_zsh

elif [ "$(uname)" == "Linux" ]; then
    info "Linux detected"

    if [ -f "/etc/arch-release" ]; then
        PROFILE="" archlinux/install_packages.bash
        success "Arch Linux packages installed."
    fi

    printf "\n"
    printf "Install Vim 8 packages natively\n"
    script/vim_packages

    printf "\nInstall XDG config and data files\n"
    script/xdg_config
    script/xdg_local
fi

#cd ${DOTFILES_ROOT} && bin/update-git

printf "\n\n"
success "All installed!"
