#!/bin/bash
# vim: set ts=4 sw=4 sts=4 et:
set -u

VIM_DIR="${HOME}/.vim"
GITHUB_DIR="${HOME}/github"

# Ensure script is run from root dotfile directory
cd "$(dirname "${0}")/.." || exit 1
DOTFILES_ROOT="$(pwd)"

# Source reusable bash functions
printf "DOTFILES_ROOT: %s\n" "${DOTFILES_ROOT}"
printf "Trying to source: %s\n" "${DOTFILES_ROOT}/bash/functions.bash"
source "${DOTFILES_ROOT}"/bash/functions.bash

printf "VIM_DIR: %s\n" "${VIM_DIR}"
printf "DOTFILES_ROOT: %s\n" "${DOTFILES_ROOT}"

clone_git_repo() {
    GIT_URL="${1}"
    REPO_DIR="${2}"
    REPO_DIR_NAME="$(basename "${REPO_DIR}")"

    if [ -d "${REPO_DIR}" ]; then
        pushd "${REPO_DIR}" > /dev/null || exit 1
        git pull origin master
        success "Pulled latest for ${GIT_URL}"
        popd > /dev/null || exit 1
    else
        pushd "${GITHUB_DIR}" > /dev/null || exit 1
        git clone "${GIT_URL}" "${REPO_DIR}"
        popd > /dev/null || exit 1
        success "Cloned ${REPO_DIR_NAME}"
    fi
}

link_vim_github_plugin() {
    # Link FileType plugin to load on start
    OPT_OR_START="${1}"
    GIT_URL="${2}"
    ABSOLUTE_REPO_DIR="${3}"
    REPO_DIR="$(basename "${ABSOLUTE_REPO_DIR}")"
    PLUGIN_PARENT_DIR="${VIM_DIR}/pack/github/${OPT_OR_START}"
    PLUGIN_PATH="${PLUGIN_PARENT_DIR}/${REPO_DIR}"

    create_directory "${PLUGIN_PARENT_DIR}"

    clone_git_repo "${GIT_URL}" "${ABSOLUTE_REPO_DIR}"

    if [ ! -h "${PLUGIN_PATH}" ]; then
        ln -s "${ABSOLUTE_REPO_DIR}" "${PLUGIN_PATH}"
        success "Linked ${ABSOLUTE_REPO_DIR} to ${PLUGIN_PATH}"
    else
        user "${PLUGIN_PATH} already symlinked"
    fi
    printf "\n"
}

# File type plugins
link_vim_github_plugin opt 'https://github.com/gregsexton/MatchTag.git' "${GITHUB_DIR}/MatchTag"
link_vim_github_plugin opt 'https://github.com/hashivim/vim-terraform.git' "${GITHUB_DIR}/vim-terraform"
link_vim_github_plugin opt 'https://github.com/martinda/Jenkinsfile-vim-syntax.git' "${GITHUB_DIR}/Jenkinsfile-vim-syntax"
link_vim_github_plugin opt 'https://github.com/pearofducks/ansible-vim.git' "${GITHUB_DIR}/ansible-vim"
#link_vim_github_plugin opt 'https://github.com/saltstack/salt-vim.git' "${GITHUB_DIR}/salt-vim"
link_vim_github_plugin "start" 'https://github.com/preservim/nerdtree.git' "${GITHUB_DIR}/nerdtree"
#link_vim_github_plugin opt 'https://github.com/scrooloose/syntastic.git' "${GITHUB_DIR}/syntastic"
link_vim_github_plugin opt 'https://github.com/tpope/vim-sensible.git' "${GITHUB_DIR}/vim-sensible"
link_vim_github_plugin opt 'https://github.com/tpope/vim-surround.git' "${GITHUB_DIR}/vim-surround"
link_vim_github_plugin "start" 'https://github.com/dense-analysis/ale.git' "${GITHUB_DIR}/ale"
link_vim_github_plugin "start" 'https://github.com/codota/tabnine-vim.git' "${GITHUB_DIR}/tabnine-vim"
# git clone --depth 1 https://github.com/codota/tabnine-vim

# Colour Schemes
#link_vim_github_plugin opt 'https://github.com/altercation/vim-colors-solarized.git' "${GITHUB_DIR}/vim-colors-solarized"
#link_vim_github_plugin opt 'https://github.com/joshdick/onedark.vim.git' "${GITHUB_DIR}/onedark.vim"
#link_vim_github_plugin opt 'https://github.com/drewtempelmeyer/palenight.vim.git' "${GITHUB_DIR}/palenight.vim"
link_vim_github_plugin opt 'https://github.com/dracula/vim.git' "${GITHUB_DIR}/dracula"

printf "\n"
