#!/bin/bash
# vim: set ts=4 sw=4 sts=4 et:

XDG_DATA_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}"
GITHUB_DIR="${HOME}/github"

set -u

# Ensure script is run from root dotfile directory 
cd "$(dirname "$0")/.." || exit 1
DOTFILES_ROOT=$(pwd)

if [ ! -d "${XDG_DATA_HOME}" ]; then
    mkdir "${XDG_DATA_HOME}"
    success "Created directory ${XDG_DATA_HOME}"
fi

# Source reusable bash functions
source "${DOTFILES_ROOT}"/bash/functions.bash

printf "XDG_DATA_HOME: %s\n" "${XDG_DATA_HOME}"
printf "DOTFILES_ROOT: %s\n" "${DOTFILES_ROOT}"

function create_directory() {
    ABS_PATH="${1}"

    if [ -e "${ABS_PATH}" ]; then
        user "${ABS_PATH} exists"
    else
        mkdir -p "${ABS_PATH}"
        success "Created ${ABS_PATH}"
    fi
}

function clone_git_repo() {
    GIT_USER="${1}"
    REPO_NAME="${2}"
    REPO_URL="https://github.com/${GIT_USER}/${REPO_NAME}.git"


    if [ -d "${GITHUB_DIR}/${REPO_NAME}" ]; then
        pushd "${GITHUB_DIR}/${REPO_NAME}" > /dev/null || exit 1
        git pull origin master
        success "Pulled latest for ${REPO_NAME}"
        popd > /dev/null || exit 1
    else
        pushd "${GITHUB_DIR}" > /dev/null || exit 1
        git clone "${REPO_URL}"
        popd > /dev/null || exit 1
        success "Cloned ${REPO_NAME}"
    fi
}

function link_neovim_github_plugin() {
    # $XDG_DATA_HOME/nvim/site/pack/altercation/start
    APP="nvim"
    STARTOPT="${1}"
    GIT_USER="${2}"
    REPO_NAME="${3}"

    PLUGIN_PARENT_DIR="${XDG_DATA_HOME}/${APP}/site/pack/github/${STARTOPT}"

    create_directory "${PLUGIN_PARENT_DIR}"

    clone_git_repo "${GIT_USER}" "${REPO_NAME}"

    if [ ! -h "${PLUGIN_PARENT_DIR}/${REPO_NAME}" ]; then 
        ln -s "${GITHUB_DIR}/${REPO_NAME}" "${PLUGIN_PARENT_DIR}/${REPO_NAME}"
        success "Linked ${GITHUB_DIR}/${REPO_NAME} to ${PLUGIN_PARENT_DIR}/${REPO_NAME}"
    else
        user "${PLUGIN_PARENT_DIR}/${REPO_NAME} already symlinked"
    fi
    printf "\n"
}

# File type plugins
link_neovim_github_plugin "start" "gregsexton" "MatchTag"
link_neovim_github_plugin "start" "hashivim" "vim-terraform"
link_neovim_github_plugin "start" "martinda" "Jenkinsfile-vim-syntax"
link_neovim_github_plugin "start" "saltstack" "salt-vim"
link_neovim_github_plugin "start" "scrooloose" "nerdtree"
#link_neovim_github_plugin "start" "scrooloose" "syntastic"
link_neovim_github_plugin "start" "tpope" "vim-sensible"
link_neovim_github_plugin "start" "tpope" "vim-surround"
link_neovim_github_plugin "start" "vim-scripts" "groovyindent-unix"
link_neovim_github_plugin "start" "w0rp" "ale"
link_neovim_github_plugin "start" "zxqfl" "tabnine-vim"

# Colour Schemes
link_neovim_github_plugin "opt" "joshdick" "onedark.vim"
link_neovim_github_plugin "opt" "drewtempelmeyer" "palenight.vim"

printf "\n"
