#!/bin/bash

# See setup instructions here:
# https://github.com/tabnine/YouCompleteMe

if [ ! -d ~/github/YouCompleteMe ]; then
    cd ~/github || exit 1
    git clone https://github.com/tabnine/YouCompleteMe.git
fi

cd ~/github/YouCompleteMe || exit 1
git pull origin master
git submodule update --init --recursive

python install.py --all


mkdir -p ~/.vim/pack/github/start
cd ~/.vim/pack/github/start || exit 1
ln -sf ~/github/YouCompleteMe .

mkdir -p ~/.local/share/nvim/site/pack/github/start
cd ~/.local/share/nvim/site/pack/github/start || exit 1
ln -sf ~/github/YouCompleteMe .
